apiVersion: v1
kind: Pod
metadata:
  name: helm-practice-1
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: command-demo-container
      image: yg18/website
      ports:
        - containerPort: 3000
          name: "http"
      env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: message
  restartPolicy: OnFailure
